name: Publish
on:
  pull_request:
    branches: dev
    types:
      - closed

jobs:
  publish-itchio:
    if: github.event.pull_request.merged == true
    name: Publish ItchIO
    strategy:
      matrix:
        channel:
          - windows
          - macos
          - linux
          - webgl
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GH_PAT }}
          repository: neotene/spacebuild
          name: 'spacebuild_${{ github.ref_name }}_${{ matrix.channel }}'
          path: 'spacebuild_${{ github.ref_name }}_${{ matrix.channel }}'
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: 'spacebuild_${{ github.ref_name }}_${{ matrix.channel }}'
          itchUsername: ${{secrets.ITCHIO_USERNAME}}
          itchGameId: ${{ secrets.ITCHIO_GAME }}
          buildChannel: ${{ matrix.channel }}
